//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package fi.metacity.klmobi;

import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.os.Handler;
import android.text.Editable;
import android.text.TextWatcher;
import android.util.Log;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.View.OnLongClickListener;
import android.view.ViewGroup.LayoutParams;
import android.widget.ArrayAdapter;
import android.widget.AutoCompleteTextView;
import android.widget.ImageButton;
import android.widget.TextView;
import com.googlecode.androidannotations.api.BackgroundExecutor;
import fi.metacity.klmobi.R.id;
import fi.metacity.klmobi.R.layout;

public final class MainActivity_
    extends MainActivity
{

    private Handler handler_ = new Handler();

    @Override
    public void onCreate(Bundle savedInstanceState) {
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        setContentView(layout.activity_main);
    }

    private void init_(Bundle savedInstanceState) {
        mPreferences = new Preferences_(this);
        mGlobals = ((MHApp) this.getApplication());
    }

    private void afterSetContentView_() {
        mEndText = ((AutoCompleteTextView) findViewById(id.endText));
        mEndClearButton = ((ImageButton) findViewById(id.endClearBtn));
        mStartClearButton = ((ImageButton) findViewById(id.startClearBtn));
        mDateText = ((TextView) findViewById(id.dateText));
        mStartText = ((AutoCompleteTextView) findViewById(id.startText));
        mTimeText = ((TextView) findViewById(id.timeText));
        {
            View view = findViewById(id.dateText);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        MainActivity_.this.pickDate();
                    }

                }
                );
            }
        }
        {
            View view = findViewById(id.swapBtn);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        MainActivity_.this.swapAddresses();
                    }

                }
                );
            }
        }
        {
            View view = findViewById(id.startClearBtn);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        MainActivity_.this.clearStart();
                    }

                }
                );
            }
        }
        {
            View view = findViewById(id.timeText);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        MainActivity_.this.pickTime();
                    }

                }
                );
            }
        }
        {
            View view = findViewById(id.endClearBtn);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        MainActivity_.this.clearEnd();
                    }

                }
                );
            }
        }
        {
            View view = findViewById(id.swapBtn);
            if (view!= null) {
                view.setOnLongClickListener(new OnLongClickListener() {


                    @Override
                    public boolean onLongClick(View view) {
                        MainActivity_.this.showSwapHint();
                        return true;
                    }

                }
                );
            }
        }
        {
            final TextView view = ((TextView) findViewById(id.startText));
            if (view!= null) {
                view.addTextChangedListener(new TextWatcher() {


                    @Override
                    public void afterTextChanged(Editable s) {
                    }

                    @Override
                    public void onTextChanged(java.lang.CharSequence s, int start, int before, int count) {
                        MainActivity_.this.onTextChangesOnSomeTextViews(view, s);
                    }

                    @Override
                    public void beforeTextChanged(java.lang.CharSequence s, int start, int count, int after) {
                    }

                }
                );
            }
        }
        {
            final TextView view = ((TextView) findViewById(id.endText));
            if (view!= null) {
                view.addTextChangedListener(new TextWatcher() {


                    @Override
                    public void afterTextChanged(Editable s) {
                    }

                    @Override
                    public void onTextChanged(java.lang.CharSequence s, int start, int before, int count) {
                        MainActivity_.this.onTextChangesOnSomeTextViews(view, s);
                    }

                    @Override
                    public void beforeTextChanged(java.lang.CharSequence s, int start, int count, int after) {
                    }

                }
                );
            }
        }
        initialize();
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        afterSetContentView_();
    }

    public static MainActivity_.IntentBuilder_ intent(Context context) {
        return new MainActivity_.IntentBuilder_(context);
    }

    @Override
    public void setAddressAdapter(final TextView tv, final ArrayAdapter<Address> adapter) {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                try {
                    MainActivity_.super.setAddressAdapter(tv, adapter);
                } catch (RuntimeException e) {
                    Log.e("MainActivity_", "A runtime exception was thrown while executing code in a runnable", e);
                }
            }

        }
        );
    }

    @Override
    public void fetchToken() {
        BackgroundExecutor.execute(new Runnable() {


            @Override
            public void run() {
                try {
                    MainActivity_.super.fetchToken();
                } catch (RuntimeException e) {
                    Log.e("MainActivity_", "A runtime exception was thrown while executing code in a runnable", e);
                }
            }

        }
        );
    }

    @Override
    public void searchAddresses(final TextView addressInput, final java.lang.CharSequence text) {
        BackgroundExecutor.execute(new Runnable() {


            @Override
            public void run() {
                try {
                    MainActivity_.super.searchAddresses(addressInput, text);
                } catch (RuntimeException e) {
                    Log.e("MainActivity_", "A runtime exception was thrown while executing code in a runnable", e);
                }
            }

        }
        );
    }

    public static class IntentBuilder_ {

        private Context context_;
        private final Intent intent_;

        public IntentBuilder_(Context context) {
            context_ = context;
            intent_ = new Intent(context, MainActivity_.class);
        }

        public Intent get() {
            return intent_;
        }

        public MainActivity_.IntentBuilder_ flags(int flags) {
            intent_.setFlags(flags);
            return this;
        }

        public void start() {
            context_.startActivity(intent_);
        }

        public void startForResult(int requestCode) {
            if (context_ instanceof Activity) {
                ((Activity) context_).startActivityForResult(intent_, requestCode);
            } else {
                context_.startActivity(intent_);
            }
        }

    }

}
