//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package fi.metacity.klmobi;

import android.content.Context;
import android.content.SharedPreferences;
import com.googlecode.androidannotations.api.sharedpreferences.EditorHelper;
import com.googlecode.androidannotations.api.sharedpreferences.IntPrefEditorField;
import com.googlecode.androidannotations.api.sharedpreferences.IntPrefField;
import com.googlecode.androidannotations.api.sharedpreferences.SharedPreferencesHelper;
import com.googlecode.androidannotations.api.sharedpreferences.StringPrefEditorField;
import com.googlecode.androidannotations.api.sharedpreferences.StringPrefField;

public final class Preferences_
    extends SharedPreferencesHelper
{


    public Preferences_(Context context) {
        super(context.getSharedPreferences("Preferences", 0));
    }

    public Preferences_.PreferencesEditor_ edit() {
        return new Preferences_.PreferencesEditor_(getSharedPreferences());
    }

    public StringPrefField baseUrl() {
        return stringField("baseUrl", "http://hameenlinna.matkahuolto.info/");
    }

    public IntPrefField selectedCityIndex() {
        return intField("selectedCityIndex", 0);
    }

    public final static class PreferencesEditor_
        extends EditorHelper<Preferences_.PreferencesEditor_>
    {


        PreferencesEditor_(SharedPreferences sharedPreferences) {
            super(sharedPreferences);
        }

        public StringPrefEditorField<Preferences_.PreferencesEditor_> baseUrl() {
            return stringField("baseUrl");
        }

        public IntPrefEditorField<Preferences_.PreferencesEditor_> selectedCityIndex() {
            return intField("selectedCityIndex");
        }

    }

}
